spring.application.name=api-gateway
server.port=8765

# Enable service discovery for the API Gateway
spring.cloud.gateway.server.webflux.discovery.locator.enabled=true 
# Convert service IDs to lowercase to match the naming convention used by Eureka
spring.cloud.gateway.server.webflux.discovery.locator.lower-case-service-id=true