spring.application.name=SpringSecutity

# # spring.security.user.name=king
# spring.security.user.password=7567

spring.datasource.url=jdbc:postgresql://localhost:5432/UserDetails
spring.datasource.username=postgres
spring.datasource.password=7567