spring.application.name=quiz-service
spring.datasource.url=jdbc:postgresql://localhost:5432/QuizDB
spring.datasource.username=postgres
spring.datasource.password=7567
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect